import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const toAbsolute = (p) => path.resolve(__dirname, p);

// Read index.html template generated by client build
const template = fs.readFileSync(toAbsolute('dist/index.html'), 'utf-8');

// Import the render function from the server bundle
import { render } from './dist/server/entry-server.js';

// Define the routes we want to pre-render
const routes = [
  '/',
  '/about',
  '/vehicles',
  '/packages',
  '/gallery',
  '/contact',
  '/privacy-policy',
  '/terms-and-conditions',
  '/madurai-taxi-service',
  '/madurai-airport-taxi',
  '/madurai-tour-packages',
  '/madurai-to-rameswaram-taxi',
  '/madurai-to-kodaikanal-taxi',
  '/tempo-traveller-rental-madurai'
];

// Define static SEO metadata for each route
const routeMetadata = {
  '/': {
    title: 'Madurai Best Tours and Travels | Taxi Service, Airport Pickup & Tour Packages',
    description: 'Madurai Best Tours and Travels offers taxi services, airport pickup and drop, outstation cabs, Tempo Traveller rental, Madurai sightseeing, Rameswaram tour packages, Kodaikanal tours, Ooty tours and South India holiday packages.'
  },
  '/about': {
    title: 'About Us | Madurai Best Tours and Travels | South India Taxi',
    description: 'Learn more about Madurai Best Tours and Travels (known also as Madurai Best Travels and Madurai Best Tours). We are your trusted travel partner in South India since 2015, providing premium taxi services, outstation cabs, and custom tours.'
  },
  '/vehicles': {
    title: 'Our Premium Fleet - Cabs & Tempo Travellers | Madurai Best Tours and Travels',
    description: 'Choose from our wide range of well-maintained vehicles including Swift Dzire, Innova Crysta, Tempo Traveller, and Urbania for a comfortable ride in Madurai with Madurai Best Tours and Travels.'
  },
  '/packages': {
    title: 'South India Tour Packages | Madurai Best Tours and Travels',
    description: 'Book customized tour packages for Madurai local sightseeing, Rameswaram, Kodaikanal, Ooty, Munnar, Kanyakumari, and Cochin with expert guides from Madurai Best Tours and Travels.'
  },
  '/gallery': {
    title: 'Our Journey Gallery | Madurai Best Tours and Travels',
    description: 'View glimpses of beautiful destinations, happy moments, and tour experiences with our travelers across South India - Madurai Best Tours and Travels.'
  },
  '/contact': {
    title: 'Contact Us | Madurai Best Tours and Travels | 24/7 Cab Booking',
    description: 'Get in touch with Madurai Best Tours and Travels. Contact us 24/7 for booking cabs, tempo travellers, and custom South India tour packages.'
  },
  '/privacy-policy': {
    title: 'Privacy Policy | Madurai Best Tours and Travels',
    description: 'Read the privacy policy of Madurai Best Tours and Travels regarding user data and booking details.'
  },
  '/terms-and-conditions': {
    title: 'Terms & Conditions | Madurai Best Tours and Travels',
    description: 'Review the terms and conditions for booking taxis, cabs, and tour packages with Madurai Best Tours and Travels.'
  },
  '/madurai-taxi-service': {
    title: 'Madurai Taxi Service & Cab Booking | Madurai Best Tours and Travels',
    description: 'Book reliable and affordable Madurai taxi service for local sightseeing, outstation drops, and airport transfers with premium vehicles from Madurai Best Tours and Travels.'
  },
  '/madurai-airport-taxi': {
    title: 'Madurai Airport Taxi & Transfers | Madurai Best Tours and Travels',
    description: 'Pre-book your Madurai Airport taxi with Madurai Best Tours and Travels for punctual, 24/7 pickup and drop services. Avoid waiting with our premium airport cab service.'
  },
  '/madurai-tour-packages': {
    title: 'Best Madurai Tour Packages | Madurai Best Tours and Travels',
    description: 'Customized Madurai tour packages from Madurai Best Tours and Travels covering Meenakshi Temple, Rameswaram, Kodaikanal, and all major South Indian destinations.'
  },
  '/madurai-to-rameswaram-taxi': {
    title: 'Madurai to Rameswaram Taxi & Cabs | Madurai Best Tours and Travels',
    description: 'Book a safe and comfortable Madurai to Rameswaram taxi. We offer affordable one-way drops and comprehensive round-trip packages with Madurai Best Tours and Travels.'
  },
  '/madurai-to-kodaikanal-taxi': {
    title: 'Madurai to Kodaikanal Taxi Service | Madurai Best Tours and Travels',
    description: 'Enjoy a scenic drive with our Madurai to Kodaikanal taxi service from Madurai Best Tours and Travels. Expert mountain drivers for a safe journey to the hill station.'
  },
  '/tempo-traveller-rental-madurai': {
    title: 'Tempo Traveller Rental in Madurai | Madurai Best Tours and Travels',
    description: 'Book spacious 12, 14, and 18-seater Tempo Travellers or premium Force Urbanias in Madurai for comfortable group and family travel with Madurai Best Tours and Travels.'
  }
};

async function runPrerender() {
  console.log('Starting static site pre-rendering with SEO metadata injection...');

  for (const url of routes) {
    console.log(`Pre-rendering route: ${url}`);
    
    // Render the app for this specific route
    const appHtml = render(url);
    
    // Inject the rendered HTML into the template
    let html = template.replace('<!--ssr-outlet-->', appHtml);
    
    // Get SEO metadata for this page
    const meta = routeMetadata[url] || routeMetadata['/'];
    
    // Replace Page Title
    html = html.replace(/<title>.*?<\/title>/, `<title>${meta.title}</title>`);
    
    // Replace Description meta tag (handles multi-line definition)
    html = html.replace(
      /<meta\s+name="description"[\s\S]*?content=".*?"\s*\/>/, 
      `<meta name="description" content="${meta.description}" />`
    );
    
    // Replace Open Graph Tags
    html = html.replace(
      /<meta\s+property="og:title"\s+content=".*?"\s*\/>/, 
      `<meta property="og:title" content="${meta.title}" />`
    );
    html = html.replace(
      /<meta\s+property="og:description"[\s\S]*?content=".*?"\s*\/>/, 
      `<meta property="og:description" content="${meta.description}" />`
    );
    
    // Replace Twitter Tags
    html = html.replace(
      /<meta\s+name="twitter:title"\s+content=".*?"\s*\/>/, 
      `<meta name="twitter:title" content="${meta.title}" />`
    );
    html = html.replace(
      /<meta\s+name="twitter:description"[\s\S]*?content=".*?"\s*\/>/, 
      `<meta name="twitter:description" content="${meta.description}" />`
    );
    
    // Replace Canonical Link
    const canonicalUrl = `https://www.maduraibesttoursandtravels.in${url === '/' ? '' : url}`;
    html = html.replace(
      /<link\s+rel="canonical"\s+href=".*?"\s*\/>/,
      `<link rel="canonical" href="${canonicalUrl}" />`
    );
    
    // Determine target directory and file path
    const targetDir = url === '/' ? '' : url;
    const dirPath = toAbsolute(`dist${targetDir}`);
    
    // Create directory if it doesn't exist
    if (targetDir && !fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
    
    const filePath = path.join(dirPath, 'index.html');
    fs.writeFileSync(filePath, html);
  }

  // Clean up the server bundle directory so it is not deployed
  console.log('Cleaning up server bundle...');
  fs.rmSync(toAbsolute('dist/server'), { recursive: true, force: true });

  console.log('Pre-rendering completed successfully!');
}

runPrerender().catch(console.error);
